base_url = "https://localhost/"
site_name = "development site - should run on port 80"

[[repos]]
name = "gshr"
description = "git static host repo -- generates static html for repos"
url = "https://github.com/vogtb/gshr"
published_git_url = "https://github.com/vogtb/gshr"
host_git = true

[[repos]]
name = "f7"
description = "f7 is a spreadsheet formula execution library"
url = "https://github.com/vogtb/f7"
published_git_url = "https://github.com/vogtb/f7"
host_git = true

[[repos]]
name = "spreadsheet"
description = "typeScript/javascript spreadsheet parser, with formulas"
url = "https://github.com/vogtb/spreadsheet"
published_git_url = "https://github.com/vogtb/spreadsheet"
host_git = true
