[site]
base_url = "http://localhost/"
name = "example of a couple go repos on github"

[[repos]]
name = "go-git"
description = "A highly extensible Git implementation in pure Go."
url = "https://github.com/go-git/go-git"
alt_link = "https://github.com/go-git/go-git"
