base_url = "/"
site_name = "public, self hosted git repositories"

[[repos]]
name = "gshr"
description = "git static host repo -- generates static html for repos"
url = "/Users/bvogt/dev/src/ben/gshr"
published_git_url = "git@git.vogt.world:vogtb/gshr.git"

[[repos]]
name = "www"
description = "static site for www.vogt.world"
url = "/Users/bvogt/dev/src/ben/www"
published_git_url = "git@git.vogt.world:vogtb/www.git"

[[repos]]
name = "f7"
description = "f7 is a spreadsheet formula execution library"
url = "/Users/bvogt/dev/src/ben/f7"
published_git_url = "git@git.vogt.world:vogtb/f7.git"
