base_url = "/"
site_name = "public, self hosted git repositories"

[[repos]]
name = "gshr"
description = "git static host repo -- generates static html for repos"
url = "/Users/bvogt/dev/src/ben/gshr"
published_git_url = "git@git.vogt.world:vogtb/gshr.git"
host_git = true
