base_url = "http://localhost/"
site_name = "public, self hosted git repositories"

[[repos]]
name = "gshr"
description = "git static host repo -- generates static html for repos"
url = "/Users/bvogt/dev/src/ben/gshr"
published_git_url = "github.com/vogtb/gshr"
host_git = true

[[repos]]
name = "www"
description = "static site for www.vogt.world"
url = "/Users/bvogt/dev/src/ben/www"
published_git_url = "github.com/vogtb/www"
host_git = true

[[repos]]
name = "f7"
description = "f7 is a spreadsheet formula execution library"
url = "/Users/bvogt/dev/src/ben/f7"
published_git_url = "github.com/vogtb/f7"
host_git = true
